### ISSUE TITLE
Training using synthetic data

### ISSUE THREAD

**Issue by ZikangLeng** [athn-nik/sinc#2]
Hi, thank you for releasing the great work! I am a little confused on what data the model is being trained on in the provided code and instruction. Looking at the instruction, it appears that the model is only trained on real data and not on the synthetic GPT-3 guided compositional motion data. Would it be possible for you to provide the model trained on both real and synthetic data? If not, would it be possible for you to provide the synthetic data and instructions on how I can train the model on both real and synthetic data shown in the paper. Out of curiosity, how long does training take? Thank you!

**Comment by athn-nik** [comment]
If you set `data.synthetic=true` it will train using the synthetically generated data. I will follow-up with more details and instructions, but it takes about 24hours to get the results of the paper.
